spring:
  datasource:
    initialize: true
    schema: classpath:/db/tables/hsql_database_tables.sql,classpath:/db/tables/security-schema.sql
    data: classpath:/db/users.sql,classpath:/db/h2-clients.sql,classpath:/db/scopes.sql
logging:
  level:
    ROOT: INFO
    org.springframework.security: INFO

openid:
  connect:
    server:
      issuer: ${URL_ISSIER}
      topbarTitle: OpenID Connect Server
      logoImageUrl: resources/images/openid_connect_small.png
    crypto:
      keystore:
        path: classpath:/keystore.jwks
      signing:
        defaultSignerKeyId: rsa1
        defaultSigningAlgorithmName: RS256
      encrypt:
        defaultAlgorithm: RSA1_5
        defaultDecryptionKeyId: rsa1
        defaultEncryptionKeyId: rsa1
